### PR TITLE
ALMA-2374 Continue with the Applitools test code

### PR DESCRIPTION
**Pull request by nam-tran-niteco**
Ticket: https://bdigital-jira.atlassian.net/browse/ALMA-2374

Things need to be done:
- [x] Take snapshot of 2 urls (prod and dev) then send to applitools.com to compare
- [x] Scroll down the full page during caparison
- [x] Parallel test running for multiple browsers and viewports
- [x] Support multiple browser (chrome, firefox, edge, IE)
- [x] Need to find a solution for login testing

@niklasHagner  what do you think with this list of things?

### CODE REVIEW

**Comment by niklasHagner** [comment]
Nice work cleaning up the code! and adding multiple browser was more than I'd hoped for 😃 
I don't think you need to worry about adding more features like login at the moment.
Just being able to diff a batch of pages would be enough for most cases!

**Comment by niklasHagner** [comment]
I tried running it on a mac but got an error.
`uncaughtException: Failed to set viewport size! ` in browser-builder.js 

It did manage to launch 2 chrome instances and 2 FF instances. I set focus on the first chrome instance and it did seem to manage to resize the window, but then threw this error anyways.

But maybe window-handling on macOS is a bit tricky. I wouldn't worry about adding mac support.
I'll try it on Windows tomorrow and if it works there I'm happy

**Comment by nam-tran-niteco** [comment]
Thanks @niklasHagner for your warm-heart feedback 😍 

This error `uncaughtException: Failed to set viewport size!` maybe come from browser-drivers listed in package.json, some will be broken on MacOS. I couldn't test on MacOS because of lacking Macbook 😄 
Please let me know the result of Windows testing so that I'll update the code.

Besides, I think we should consider testing with logged-in status because it'll affect MittDn or premium-article pages 😞

**Comment by niklasHagner** [comment]
Excellent! It worked


I had some issues with chrome webdriver versions (but I found a lot of bug-reports related to them, so I think it's just a matter of finding which versions work and specifying them in package.json without `^`)

Go ahead and shipit! :shipit:

**Comment by nam-tran-niteco** [comment]
Great news @niklasHagner ☺️ 

I've updated code for logged in user, so now we can test the header, MittDn page, etc with different login status ✌️ 
Please take a look and if there's nothing left, it'll be ready to go!

**Comment by niklasHagner** [comment]
Using clicks to log in seems problematic.

There are so many popups running that can potentially block any kinds of clicks.

Today there was a 1-day-offer-fullscreen-popup running and I got this error
```
WebDriverError: unknown error: Element <a href="http://dev.dn
.se/loggain?redirectToUrl=http%3a%2f%2fdev.dn.se%2f" class="header__item header_
_item--tight header__item--login js-login-button">...</a> is not clickable at po
int (1141, 39). Other element would receive the click: <div id="pwOverlay" style
="height: 100%; width: 100%; position: fixed; z-index: 888889; left: 0px; top: 0
px; background-color: rgba(0, 0, 0, 0.9); overflow-x: hidden; transition: 0.5s;"
>...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87a
f1),platform=Windows NT 10.0.15063 x86_64)
uncaughtException: WebDriverError: unknown error: Element <a href="http://dev.dn
.se/loggain?redirectToUrl=http%3a%2f%2fdev.dn.se%2f" class="header__item header_
_item--tight header__item--login js-login-button">...</a> is not clickable at po
int (1141, 39). Other element would receive the click: <div id="pwOverlay" style
="height: 100%; width: 100%; position: fixed; z-index: 888889; left: 0px; top: 0
px; background-color: rgba(0, 0, 0, 0.9); overflow-x: hidden; transition: 0.5s;"
>...</div>
```

So I'm thinking we have to add some way of disabling all those popovers (like a cookie or localstorage value) before we can rely on using clicks in automated tests against prod.

Maybe we should disable the click feature until then.

**Comment by niklasHagner** [comment]
Go ahead and merge this one, further changes can be done in a separate PR :)

:shipit:

**Pull request merged**
